#!/usr/bin/env python
# -*- coding: utf-8 -*-
import logging
import click
import csv

from apps import AppCollection
from rapidapicache import RapidAPICache
from rapidapi import RapidAPI


@click.command()
@click.option("--cache", default=".cache", type=click.Path(exists=False), help="Cache directory")
@click.option("--key", help="RapidAPI API key", required=True)
@click.option("-v", default=False, is_flag=True, help='Verbose logging', required=False)
@click.argument("filename", type=click.Path(exists=True), required=True)
def cli(cache, key, v, filename):
    logging.basicConfig(format="%(asctime)s - %(levelname)s - %(message)s", level=logging.DEBUG if v else logging.INFO)
    logger = logging.getLogger(__name__)

    coll = AppCollection(logger, RapidAPI(logger, key), RapidAPICache(logger, cache))
    # Add all application to the collection
    with open(filename) as csvfile:
        reader = csv.DictReader(csvfile)
        for row in reader:
            try:
                coll.add(row["CFBundleIdentifier"])
            except Exception as e:
                logger.debug(f"Failed to add application: {e}")


# main block
if __name__ == "__main__":
    cli()
